In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
test = pd.read_csv("datamad0819-vehicles/cars_test.csv")
train = pd.read_csv("datamad0819-vehicles/cars_train.csv")

In [3]:
display(train.head())
train.shape

,Id,city,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,...,paint_color,lat,long,county_fips,county_name,state_fips,state_code,state_name,weather,price
0,559327,baltimore,2006.0,NaN,Scion tc,excellent,4 cylinders,gas,190000.0,clean,...,blue,39.287000,-76.647600,24510.0,Baltimore City,24.0,MD,Maryland,56.0,3200
1,1429566,carbondale,2018.0,dodge,charger sxt,NaN,NaN,gas,NaN,clean,...,NaN,37.720000,-89.215800,17077.0,Jackson,17.0,IL,Illinois,48.0,30620
2,931606,thumb,1997.0,ford,f 250 2 wheel dr pickup,fair,NaN,gas,NaN,clean,...,white,43.483300,-83.383500,26157.0,Tuscola,26.0,MI,Michigan,45.0,1800
3,1265412,laredo,2003.0,ram,NaN,NaN,8 cylinders,gas,NaN,clean,...,NaN,27.850069,-99.668883,48479.0,Webb,48.0,TX,Texas,67.0,4500
4,1133731,ocala,2000.0,dodge,1500,NaN,NaN,gas,NaN,clean,...,NaN,29.165000,-81.539900,12069.0,Lake,12.0,FL,Florida,65.0,1400

(469992, 24)

In [4]:
train.describe()

,Id,year,odometer,lat,long,county_fips,state_fips,weather,price
count,4.699920e+05,468279.000000,3.165270e+05,469992.000000,469992.000000,453983.000000,453983.000000,453810.000000,4.699920e+05
mean,8.618454e+05,2004.869185,1.135850e+05,38.778918,-93.706408,28459.780131,28.373219,53.787792,9.042388e+04
std,4.974450e+05,11.944575,1.400817e+05,5.972400,16.943175,16043.644693,16.021521,7.803067,9.002479e+06
min,0.000000e+00,1900.000000,0.000000e+00,-80.218737,-178.989258,1001.000000,1.000000,29.000000,1.000000e+00
25%,4.317220e+05,2002.000000,5.800000e+04,34.920500,-105.589686,12127.000000,12.000000,48.000000,3.300000e+03
50%,8.622445e+05,2007.000000,1.067000e+05,39.405900,-88.241849,29027.000000,29.000000,53.000000,7.000000e+03
75%,1.292693e+06,2012.000000,1.520000e+05,42.559300,-81.027426,41067.000000,41.000000,59.000000,1.499900e+04
max,1.723061e+06,2019.000000,1.000000e+07,84.668794,100.903396,56045.000000,56.000000,79.000000,1.686838e+09

In [5]:
train.isnull().sum()

Id                   0
city                 0
year              1713
manufacturer     37260
make             19078
condition       191021
cylinders       188076
fuel              2844
odometer        153465
title_status       708
transmission      2447
drive           180334
size            306775
type            191640
paint_color     189613
lat                  0
long                 0
county_fips      16009
county_name      16009
state_fips       16009
state_code       16009
state_name           0
weather          16182
price                0
dtype: int64

In [6]:
print(train.columns)
print(train['drive'].value_counts())
print(train['transmission'].value_counts())

Index(['Id', 'city', 'year', 'manufacturer', 'make', 'condition', 'cylinders',
       'fuel', 'odometer', 'title_status', 'transmission', 'drive', 'size',
       'type', 'paint_color', 'lat', 'long', 'county_fips', 'county_name',
       'state_fips', 'state_code', 'state_name', 'weather', 'price'],
      dtype='object')
4wd    121087
fwd    101308
rwd     67263
Name: drive, dtype: int64
automatic    402378
manual        55363
other          9804
Name: transmission, dtype: int64

In [7]:
train["mean_price"] = train["price"].mean()
train["mean_price"]

0         90423.881419
1         90423.881419
2         90423.881419
3         90423.881419
4         90423.881419
              ...
469987    90423.881419
469988    90423.881419
469989    90423.881419
469990    90423.881419
469991    90423.881419
Name: mean_price, Length: 469992, dtype: float64

In [8]:
y = train["mean_price"]

In [9]:
X = train[["Id"]]

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

models = {
    'linear':LogisticRegression(),
    #'svm-rbf': SVC(probability=True),
    #'svm-rbf-c10': SVC(C=10,probability=True),
    #'randomforest': RandomForestClassifier(n_estimators=100),
    #'svm-linear': SVC(kernel='linear',probability=True) 
}


for label,model in models.items():
    model.fit(X,y)

/Users/fadrique/miniconda3/envs/IhKaggleComp/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: Unknown label type: 'continuous'

In [29]:
def processData(inX, hasGT=False):
    X = inX.copy()
    features = ['fuel','condition','year','manufacturer','drive','transmission','weather']
    if hasGT:
        features.append('price')
    X = X[features]
    X.loc[X['condition'].isnull(), 'condition'] = 'unknown' 
    X.loc[X['fuel'].isnull(), 'fuel'] = 'unknown' 
    X.loc[X['drive'].isnull(), 'drive'] = 'unknown' 
    X.loc[X['manufacturer'].isnull(), 'manufacturer'] = 'unknown' 
    X.loc[X['transmission'].isnull(), 'transmission'] = 'unknown' 
    X.loc[X['weather'].isnull(), 'weather'] = 0

    #X = X[~X['year'].isnull()]
    X.loc[X['year'].isnull(), 'year'] = 2015
    X = pd.get_dummies(X,columns=['fuel','condition','drive','manufacturer','transmission'])
    
    y = None
    if hasGT:
        y = X['price']
        X = X.drop(columns=['price'],axis=1)
    else:
        y = inX['Id']
    if 'manufacturer_mercedesbenz' in X.columns:
        X=X.drop(columns=['manufacturer_mercedesbenz'])
    return X, y

In [30]:
X_submission, submission_id =  processData(pd.read_csv('datamad0819-vehicles/cars_test.csv'))
X, y =  processData(pd.read_csv('datamad0819-vehicles/cars_train.csv'), True)

In [32]:
#display(set(X_submission.columns)-set(X.columns))

In [33]:
from sklearn.decomposition import PCA

pca = PCA(n_components=15)
X_train = pca.fit_transform(X) 
X_train = pd.DataFrame(X_train)
X_train_submission = pca.transform(X_submission)
X_train_submission = pd.DataFrame(X_train_submission)

In [34]:
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
models = {
#    "modelSVR": SVR(kernel="linear"),
#    "modelLinearRG": LinearRegression(),
#    "decisionTree": DecisionTreeRegressor(random_state=0)
    'randomForest': RandomForestRegressor(max_depth=3, random_state=0,n_estimators=50)
}

preds = {}

for label, model in models.items():
    print("Training {}".format(label))
    model.fit(X_train,y)
    preds[label] = model.predict(X_train_submission)

Training randomForest

In [35]:
for label, pred in preds.items():
    submission = pd.DataFrame({
        'Id': submission_id,
        'price': train["mean_price"]
    })
    display(submission.head())
    submission.to_csv('submission_mean.csv', index=False)

          Id         price
0   974298.0  90423.881419
1  1051884.0  90423.881419
2   684464.0  90423.881419
3  1255387.0  90423.881419
4  1195520.0  90423.881419

In [15]:

submission = pd.DataFrame({
    "Id": test["Id"],
    "price": train["mean_price"]
})

In [27]:

submission.to_csv('submission_mean.csv')